local function map(mode, lhs, rhs, opts)
  vim.keymap.set(mode, lhs, rhs, opts)
end

map('n', '<C-s>', ':w<CR>', {silent = true})
map('n', '<Leader>h', '<cmd>UndotreeShow<cr>', {})
map('n', '<C-e>', ':lua require("harpoon.ui").toggle_quick_menu()<CR>', {silent = true})
map('n', 'Q', '<nop>', {silent = true, noremap = true})
map('n', '<Leader>a', ':lua require("harpoon.mark").add_file()<CR>', {silent = true})
map('n', '<Leader>ff', '<cmd>Telescope find_files<CR>', {})
map('n', '<Leader>fg', '<cmd>Telescope live_grep<CR>', {})
map('n', '<Leader>fb', '<cmd>Telescope buffers<CR>', {})
map('n', '<Leader>w', '<cmd>HopWord<CR>', {})
map('n', '<Leader>l', '<cmd>HopLine<CR>', {})
map('n', '<Leader>s', '<cmd>Codi javascript<CR>', {})
map('n', '<Leader>1', ':TestFile<CR>', {silent = true})
map('n', '<Leader>2', ':TestNearest<CR>', {silent = true})
map('n', '<Leader>3', ':TestLast<CR>', {silent = true})
map('n', '<Leader>4', ':TestSuite<CR>', {silent = true})
map('n', '<Leader><Leader>x', ':call Save_and_exec()<CR>', {})
